AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example demo written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 3

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: private-lv-test
      StageName: test

  #  MyQueue:
  #    Type: AWS::SQS::QUEUE
  #    Properties:
  #      Name: dfw-warm-up

  lv-testFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lv-test
      Handler: com.demo.cloud.user.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/springboot-lambda-0.0.1-SNAPSHOT.jar
      MemorySize: 1536
      Policies: AWSLambdaBasicExecutionRole
      #      AutoPublishAlias: v1
      Timeout: 600
      Events:
        lv-testApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  #  QXDfwApi:
  #    Description: "API Gateway endpoint URL for Prod stage for QXDfw function"
  #    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com.cn/Prod/dfw/warm-up/"
  lv-testFunction:
    Description: "QXDfw Lambda Function ARN"
    Value: !GetAtt QXDfwFunction.Arn
  lv-testFunctionIamRole:
    Description: "Implicit IAM Role created for QXDfw function"
    Value: !GetAtt QXDfwFunctionRole.Arn